### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by mapo80** [grip-unina/TruFor#1]
Hi,

your work is very interesting.
I have two questions:
- Can be used to determined if a document is forged or not?
- When source code will be available? Do you have a date?

Thanks

**Comment by fabrizioguillaro** [comment]
Hi, thank you for your interest in our work.

- it depends on the type of document under analysis. For scientific documents, if the algorithm is applied on a specific image it may work (e.g. a subpanel of a figure in the document). It can have some difficulties with compound images, e.g. with plain white space between the subfigures, since Noiseprint++ behaves bad with totally uniform areas.
- The code will be available by the end of June, we will also provide our pretrained weigths
