### ISSUE TITLE
Difference in design between NoisePrint and NoisePrint++?

### ISSUE THREAD

**Issue by Mayur28** [grip-unina/TruFor#13]
Hi,

I have read the publication corresponding to this repo, and the results are truly amazing!

I have previously worked extensively with NoisePrint, and have now gone through the NoisePrint++ implementation as well - For NoisePrint, a different model is loaded, depending on the input image's QF - I see that this is not the case for NoisePrint++, therefore, I just wanted to find out why is this the case i.e., how does NoisePrint++ achieve improved results over NoisePrint whilst using a single model regardless of the QF?

Thanks!

**Comment by fabrizioguillaro** [comment]
Hi! 
In the previous version of Noiseprint, the jpeg compression was not included in the training process. Therefore, multiple models were trained for different QFs.
In Noiseprint++, this is not necessary since we now check for the QF during training (two patches that have different QFs are considered different this time). This is already a big difference, because the old Noiseprint algorithm would provide the same noiseprint if you use a single model.
You can find a complete list of the QFs and other post-processing operations (editing history) in issue #9.
