### ISSUE TITLE
Question about F1 computation

### ISSUE THREAD

**Issue by dragosconst** [grip-unina/TruFor#8]
Hello! Great work on your paper. I'm curious about something, I'm not sure why do you compute the F1 with both the initial predicted heatmap and the inverted heatmap, and then return their maximum, instead of just the F1 of the prediction? Thank you.

**Comment by fabrizioguillaro** [comment]
Hi! The reason is that an inverted heatmap is as good as the predicted heatmap. The goal is to distinguish between two distinct regions, and from a forensic point of view there is no distinction in labelling one region or the other as fake.
Additionally, in training datasets, the area marked as fake is typically the smaller of the two, so if a test image has a forged area bigger than the pristine area, it might result in an inverted prediction (which would be good anyway, as 
 previously explained)
